version: '3.7'
services:
  db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: postgres
      ports:
        - '5432:5432'
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./sql/usda.sql:/docker-entrypoint-initdb.d/usda.sql
      healthcheck:
        test: pg_isready -U postgres
        interval: 10s
        timeout: 5s
        retries: 5
  jupyter:
        image: jupyter/scipy-notebook
        ports:
          - 8888:8888
        container_name: scipy-notebook-container
        volumes: 
          - ./jup_notebooks:/home/jovyan/work
        depends-on: 
          db:
            condition: service_healthy
  
  plotly-dashboard:
        image: dedier/plotly-dashboard
        ports:
          - 8050:8050
        container_name: plotly-dashboard
        depends-on: 
          - jupyter
