version: '3.7'
services:
  db:
      image: postgres:latest
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: postgres
      ports:
        - '5438:5432'
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./sql/usda.sql:/docker-entrypoint-initdb.d/usda.sql
  jupyter:
        image: jupyter/scipy-notebook
        ports:
          - 8888:8888
        container_name: scipy-notebook-container
        volumes: 
          - ./jupyter-notebooks:/var/lib/jupyter-notebooks
  
